In [2]:
import torch
import matplotlib.pyplot as plt
import numpy as np


print(torch.__version__)

2.9.0


In [8]:
file_path = "/Users/baxtiyorbekmurodov/Desktop/math2LLM/data/input.txt"

with open(file_path, 'r') as f:
    text = f.read()

In [9]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(vocab_size)
print("".join(chars))

65

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [10]:
stoi = {c:i for i,c in enumerate(chars)}
itoi = {i:c for i, c in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda tokens: ''.join([itoi[t] for t in tokens])

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [11]:
data = torch.tensor(encode(text), dtype=torch.long)

In [12]:
print(data.dtype)
print(data.ndim)
print(data[:5])

torch.int64
1
tensor([18, 47, 56, 57, 58])


In [13]:
# spliting data into train/ val: 90% for training
n = len(data)
tr_size = int(n *0.9)
train_data = data[:tr_size]
val_data = data[tr_size:]

print(n); print(len(train_data) / n); print(len(val_data)/n)

1115394
0.8999994620734916
0.10000053792650848


In [14]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size+1:]

for i in range(block_size):
  context = x[:i+1]
  target = y[i]
  print(f"Input: {context} --> target={target}")

Input: tensor([18]) --> target=47
Input: tensor([18, 47]) --> target=56
Input: tensor([18, 47, 56]) --> target=57
Input: tensor([18, 47, 56, 57]) --> target=58
Input: tensor([18, 47, 56, 57, 58]) --> target=1
Input: tensor([18, 47, 56, 57, 58,  1]) --> target=15
Input: tensor([18, 47, 56, 57, 58,  1, 15]) --> target=47
Input: tensor([18, 47, 56, 57, 58,  1, 15, 47]) --> target=58


In [15]:
torch.manual_seed(1332)

batch_size = 4
block_size = batch_size * 2


def get_batch(split :str):
    # generates small batch for X input and y target
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size, ))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x, y



In [16]:
xb, yb = get_batch("train")

print(xb)
print(yb)
print("-"*32)


for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]

        print(f'Input: {context.tolist()} --> target={target}')


tensor([[44,  1, 61, 47, 58, 46,  1, 63],
        [27, 44,  1, 53, 59, 56,  1, 45],
        [40, 59, 58,  1, 39,  1, 57, 50],
        [ 1, 61, 46, 39, 58,  6,  1, 53]])
tensor([[ 1, 61, 47, 58, 46,  1, 63, 53],
        [44,  1, 53, 59, 56,  1, 45, 56],
        [59, 58,  1, 39,  1, 57, 50, 47],
        [61, 46, 39, 58,  6,  1, 53,  5]])
--------------------------------
Input: [44] --> target=1
Input: [44, 1] --> target=61
Input: [44, 1, 61] --> target=47
Input: [44, 1, 61, 47] --> target=58
Input: [44, 1, 61, 47, 58] --> target=46
Input: [44, 1, 61, 47, 58, 46] --> target=1
Input: [44, 1, 61, 47, 58, 46, 1] --> target=63
Input: [44, 1, 61, 47, 58, 46, 1, 63] --> target=53
Input: [27] --> target=44
Input: [27, 44] --> target=1
Input: [27, 44, 1] --> target=53
Input: [27, 44, 1, 53] --> target=59
Input: [27, 44, 1, 53, 59] --> target=56
Input: [27, 44, 1, 53, 59, 56] --> target=1
Input: [27, 44, 1, 53, 59, 56, 1] --> target=45
Input: [27, 44, 1, 53, 59, 56, 1, 45] --> target=56
Input: [40

In [17]:
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1332)


class BiagramModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets=None):
                
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(-1)  
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):

        for i in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]

            probs = F.softmax(logits, dim=-1)

            idx_next = torch.multinomial(probs, num_samples=1)

            idx = torch.cat((idx, idx_next), dim=1)
        
        return idx
        
    
model = BiagramModel(vocab_size)
out, loss = model(xb, yb)
print(out.shape); 
print(loss)

idx = torch.zeros((1, 1), dtype=torch.long)

print(decode(model.generate(idx, 60)[0].tolist()))

torch.Size([32, 65])
tensor(4.6546, grad_fn=<NllLossBackward0>)

javIQVz.k'dLgki,qPmetcpTLlaXV;TIJ&mqNHwMc'CbML
$PeTlrNQNJvTb


In [18]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [19]:
batch_size = 32

epochs = 10000

for i in range(epochs):

    xb, yb = get_batch("train")

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(f'Iter: {i+1} -> loss={loss.item()}')

Iter: 10000 -> loss=2.3910069465637207


In [20]:
idx = torch.zeros((1, 1), dtype=torch.long)

print(decode(model.generate(idx, 700)[0].tolist()))


CILLLERDYi?
YO, ss,
Anth--womb
NThenuthen

The
If mioth s st heereakesthe; gavend, meinthar athero s I and bulft CE:
Myshin Prss har od d inteaESifon agh myovert to me I t, hikspulis omsonoutous mulo the mangar,

th wharit, w'dy ryo your fe ac sices, wofahous d on bonod al e ivoonfonem, o,
PERY hont l do anghase fed t myou wad

Th olas ttinrthol oJBESToflinony Ans t mere nond o'
I th thon her mathank datevion citondor:
I swind Ca ak
Whate acou bue sin?
SThe falisthatheancok:
TY t?.
GBEr,
Doold hedecolerare th'Sanmo Y:
SVINZAn ou isoren r.
Youertl;

QUS:
Wirispo h it, ige lle lef, n towd, clifofr inden:
Uty MENThig t for'derm;
TI k?
Pe Pouait y windonged wero niemeenre y, n wit ak, we ceest p


# Mathematical trick of Attention

In [36]:
torch.manual_seed(42)
a = torch.ones(3, 3)
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b

print('A->', a)
print('\nB->', b)

print('\nC->', c)

A-> tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

B-> tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])

C-> tensor([[14., 16.],
        [14., 16.],
        [14., 16.]])


In [37]:
torch.tril(a)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])